# Generated by Django 4.1.2 on 2022-11-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_course_lesson_courseteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='delited',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='delited',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='delited',
        ),
        migrations.RemoveField(
            model_name='news',
            name='delited',
        ),
        migrations.AddField(
            model_name='course',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения'),
        ),
    ]
