# Generated by Django 4.1.2 on 2022-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего изменения'),
        ),
    ]
